language: groovy
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "616slayer616-github"
    token: $sonarKey
script:
  - ./gradlew build -s
  - ./gradlew sonarqube
branches:
  only:
    - master
